theme: minima
title: Julian Eskandar: Professional Portfolio
description: I am a Physics major at the University of Connecticut, on track to graduate in May of 2026. I am especially interested in Quantum ELectrodynamics as well as the phenomenon of ressonance. This page will present work the I have done during my time at Uconn.  

